---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dataaggregator-backend-hpa
  namespace: dataaggregator
  labels:
    app.kubernetes.io/name: data-aggregator
    app.kubernetes.io/component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dataaggregator-backend
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dataaggregator-frontend-hpa
  namespace: dataaggregator
  labels:
    app.kubernetes.io/name: data-aggregator
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dataaggregator-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
