# Test Configuration - YAML Format
# Data Aggregator Platform Testing Framework

execution:
  stages:
    - backend_unit
    - backend_integration
    - frontend_unit
    - frontend_integration
    - e2e
    - performance
    - security

  parallel:
    enabled: true
    backend_workers: 4
    frontend_workers: "50%"
    e2e_workers: 2

  timeouts:
    unit_test: 10
    integration_test: 30
    e2e_test: 60
    performance_test: 120

artifacts:
  capture_level: essential
  coverage:
    enabled: true
    backend_threshold: 80
    frontend_threshold: 80

environment:
  database:
    host: localhost
    port: 5433
    name: dataaggregator_test
  redis:
    host: localhost
    port: 6380
