# Test Configuration
# YAML configuration for test execution preferences

failure_artifacts:
  # Options: minimal, essential, comprehensive
  level: essential

  capture:
    stack_traces: true
    html_reports: true
    screenshots: true      # E2E only
    videos: false         # E2E only, expensive
    database_dumps: false # Large files, enable for debugging
    api_logs: true
    app_logs: true
    browser_logs: false   # E2E only

  retention:
    max_runs: 10         # Keep last 10 test runs
    max_days: 30         # Or 30 days, whichever comes first
    max_size_mb: 5000    # Auto-cleanup if reports exceed 5GB

test_execution:
  fail_fast: true        # Stop between stages on failure
  parallel_execution: true

  workers:
    backend_unit: 4
    frontend_unit: "50%"  # 50% of available CPUs
    e2e: 2

  timeouts:
    unit_test: 10        # seconds
    integration_test: 30
    e2e_test: 60

coverage_thresholds:
  backend:
    overall: 80
    models: 90
    services: 85
    endpoints: 90

  frontend:
    overall: 80
    components: 75
    hooks: 85
    pages: 75

reporting:
  formats:
    - console
    - html
    - json
    - xml           # For CI/CD

  console:
    colors: true
    verbose: true
    show_progress: true

  html:
    open_browser: false  # true in local, false in CI

notifications:
  enabled: false         # Set to true for Slack/Email
  slack_webhook: ""
  email_recipients: []
